## @(#) :  pnpm-workspace.yaml
#
# @version  0.0.1
# @author   Furukawa Atsushi <atsushifx@gmail.com>
# @since      2025-02-16
# @license    MIT
#
# @desc<<
#
# monorepo workspaces settings for pnpm
#
#<<

packages:
  - "apps"
  - "configs"
  - "apps/*"
  - "packages/*"
