## src: ./configs/secretlint.config.yaml
## @(#) : secretlint config files using yaml
#
#
# Copyright (c) 2025 atsushifx <http://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

rules:
  - id: "@secretlint/secretlint-rule-preset-recommend"
