# src: ./.github/workflows/ci-scan-secrets.yml
# @(#) : Caller workflow for secret scanning in .github repository
#
# Copyright (c) 2025- atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: "CI Scan Secrets"

# Minimal permissions following security best practices
permissions:
  contents: read

on:
  push:

  pull_request:
    branches:
      - main
      - master
      - releases

  workflow_dispatch:

jobs:
  scan-betterleaks:
    name: Betterleaks Secret Scan
    permissions:
      contents: read
    uses: aglabo/ci-platform/.github/workflows/ru-scan-betterleaks.yml@9cc4b15bf10854ecc0fc2ea0a419d96566ea8bde # v0.3.3
